1.	Write a NumPy program to create one-dimensional array of single, two and three digit numbers.

In [1]:
import numpy as np
nums = np.arange(1, 21)
print("One-dimensional array of single digit numbers:")
print(nums)
nums = np.arange(10, 21)
print("\nOne-dimensional array of two digit numbers:")
print(nums)
nums = np.arange(100, 201)
print("\nOne-dimensional array of three digit numbers:")
print(nums)

One-dimensional array of single digit numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of two digit numbers:
[10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of three digit numbers:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [ ]:
2.Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros. 

In [2]:
import numpy as np
nums = np.zeros(shape=(5, 6), dtype='int')
print("Original array:")
print(nums)
nums[::2, ::2] = 3
nums[1::2, ::2] = 7
print("\nNew array:")
print(nums)

Original array:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

New array:
[[3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]]


In [ ]:
3.Write a program to sum all the elements of NumPy array.

In [3]:
import numpy as np
x = np.array([[0,1],[2,3],[4,5]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))

Original array:
[[0 1]
 [2 3]
 [4 5]]
Sum of all elements:
15


In [ ]:
4.Write a NumPy program to convert one dimensional array to two dimensional array .

In [4]:
import numpy as np
a = np.array([[10],[20],[30]])
b = np.array([[60],[70],[80]])
c = np.dstack((a, b))
print(c)

[[[10 60]]

 [[20 70]]

 [[30 80]]]


In [ ]:
5.Write a NumPy program to compute the determinant of an array.

In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


In [ ]:
6.Write a NumPy program to compute the inverse of a given matrix.

In [6]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
7.Write a NumPy program to create an array with values ranging from 12 to 38.

In [7]:
import numpy as np
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
8.Write a NumPy program to append values to the end of an array. Expected Output: Original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [8]:
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
